// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58FNx2ZitNmnT8K0SkZ8yQmslQkBKsU0',
    appId: '1:406030063656:android:a6d46a5ea7dacf8344fd1d',
    messagingSenderId: '406030063656',
    projectId: 'neptune-recyclers-live',
    databaseURL: 'https://neptune-recyclers-live-default-rtdb.firebaseio.com',
    storageBucket: 'neptune-recyclers-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNafDleCj0JNZjeXgARAqhX1j_bmLmtoY',
    appId: '1:406030063656:ios:691f9918669dc4df44fd1d',
    messagingSenderId: '406030063656',
    projectId: 'neptune-recyclers-live',
    databaseURL: 'https://neptune-recyclers-live-default-rtdb.firebaseio.com',
    storageBucket: 'neptune-recyclers-live.firebasestorage.app',
    iosBundleId: 'com.neptune.neptuneRecyclers',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8FEqJ1T-CDBCKBit13fH8AzKjmPh1hg',
    appId: '1:406030063656:web:65258bf1afe21bfd44fd1d',
    messagingSenderId: '406030063656',
    projectId: 'neptune-recyclers-live',
    authDomain: 'neptune-recyclers-live.firebaseapp.com',
    databaseURL: 'https://neptune-recyclers-live-default-rtdb.firebaseio.com',
    storageBucket: 'neptune-recyclers-live.firebasestorage.app',
  );

}